CREATE TABLE DETALJI_NARUDZBE (
	ID_NARUDZBE CHAR(6),
	ID_OPREME CHAR(6),
	KOLICINA INT CHECK(KOLICINA > 0),
	CONSTRAINT PK_DETALJI_NARUDZBE PRIMARY KEY(ID_NARUDZBE, ID_OPREME),
	CONSTRAINT FK_DETALJI_NARUDZBE_NARUDZBA FOREIGN KEY(ID_NARUDZBE)
	REFERENCES NARUDZBA(ID_NAR),
	CONSTRAINT FK_DETALJI_NARUDZBE_PROIZVOD FOREIGN KEY(ID_OPREME)
	REFERENCES OPREMA(ID_OPR)
); 
